language: node_js
node_js:
    - "0.10"
    - "4.2"
    - "5.0"

os:
    - linux
#   - osx

matrix:
    allow_failures:
        - os: osx
        - node_js: 5.0
    fast_finish: true

services:
    - elasticsearch

# wait for elasticsearch to start up
before_script:
  - chmod -w ./test/spool/nowrite
  - sleep 10

after_success:
  - npm install istanbul codecov.io
  - NODE_ENV=cov ./node_modules/istanbul/lib/cli.js cover ./node_modules/mocha/bin/_mocha -- -R spec
  - cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js

sudo: false
